<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>course_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the course simulation (TurtleBot3 in Gazebo, optional GUI).</description>
  <maintainer email="pawel.irzyk6@gmail.com">Pawel Irzyk</maintainer>
  <license>Apache-2.0</license>
  <exec_depend>turtlebot3_gazebo</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
